-- Migration 003: Enhance rewards table with inventory tracking
-- Adds quantity management columns needed for the Rewards Engine.
--
-- NOTE: SQLite ALTER TABLE does not support IF NOT EXISTS.
-- All column additions (total_quantity, claimed_count, is_active, rule_match, reward_code)
-- are handled dynamically in lib/db.ts AFTER migrations run, using pragma table_info().
--
-- Indexes that depend on those columns (idx_rewards_is_active, idx_leads_reward_status)
-- are also deferred to lib/db.ts for the same reason; they cannot be created here
-- because the columns they reference may not exist yet on a fresh database.
--
-- This file intentionally left without DDL statements.
SELECT 1; -- no-op placeholder so the file is not empty
